In [16]:
import sys
import warnings
warnings.filterwarnings("ignore")
sys.path.append("..")
import numpy as np

from matplotlib import pyplot as plt

from codes import make_env

In [17]:
env = make_env("MiniGrid-DistShift1-v0",
                flat_obs=True,
                normalize_reward=True,
                penalize_death=True,
                reward_amplification=1.0,
                mx_reward=1.0,
                gamma=0.9,
                )

In [18]:
obs, _ = env.reset(seed=42)

In [19]:
obs = obs.reshape((-1, 3))[:, 0]

In [23]:
obs.reshape(7, 5)

array([[10,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 8,  1,  1,  1,  1]], dtype=uint8)

In [24]:
obs = env.step(1)[0]

In [25]:
obs.reshape((-1, 3))[:, 0].reshape(7, 5)

array([[ 1, 10,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 8,  1,  1,  1,  1]], dtype=uint8)

In [26]:
obs, reward, term, trunc, _ = env.step(1)

In [27]:
obs.reshape((-1, 3))[:, 0].reshape(7, 5)

array([[ 1,  1, 10,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 8,  1,  1,  1,  1]], dtype=uint8)

In [28]:
reward

-0.09999999999999998

In [29]:
env.step(0)
env.step(0)
env.step(0)
env.step(0)
env.step(0)
env.step(0)

(array([ 1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,
         0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  9,  0,  0,  9,
         0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  9,  0,  0,  9,  0,  0,
         1,  0,  0,  1,  0,  0,  1,  0,  0,  9,  0,  0,  9,  0,  0,  1,  0,
         0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,
         0,  0,  1,  0,  0,  8,  1,  0,  1,  0,  0, 10,  0,  1,  1,  0,  0,
         1,  0,  0], dtype=uint8),
 -0.09999999999999998,
 False,
 False,
 {})

In [30]:
obs = env.step(3)[0].reshape((-1, 3))[:, 0].reshape(7, 5)

In [31]:
obs

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 8, 10,  1,  1,  1]], dtype=uint8)

In [32]:
obs, reward, term, trunc, _ = env.step(3)

In [33]:
reward

0.8642857142857143

In [34]:
obs.reshape((-1, 3))[:, 0].reshape(7, 5)

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 9,  9,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [10,  1,  1,  1,  1]], dtype=uint8)

In [13]:
print(term, trunc)

True False


In [14]:
# obs, reward, term, trunc, _ = env.step(0)
# reward

In [15]:
# obs.reshape((-1, 3))[:, 0].reshape(3, 3)